% Create ABR Figure

misc = struct( ... 
 'fileExtension', 'ABR' ...
  ); 

Stimuli = struct( ...
 'freq_hz',1000, ...
 'calibPicNum', nan, ... % Calib pic number: will populated before free-run loop 
 ... % Note: whether to use invCalib or not will depend on calib pic num. If calib-picname has 
 ... % "raw", do not run inv Calib. If it has "inv", run inverse calib. Should make invCalib default. 
 'atten_dB',    35, ...
 'cyc_flag',true,... %set to false if prefer duration instead of cycles
 'duration_cyc',1,...
 'rftime_cyc',2,...
'fast', struct( ...
        'duration_ms', 10, ... % will change to cycles eventually
        'rftime_ms',  10, ... % will also be cycles eventually
        'period_ms',  40,...% = 32.2 31.1 Hz rate
        'XstartPlot_ms',0, ...
        'XendPlot_ms',31, ...
        'CAPlength_ms',31), ...       
 'slow', struct( ...
        'duration_ms', 10, ...
        'rftime_ms',  1, ...
        'period_ms',  100, ... % 19.6, ... % = 51.1 Hz rate
        'XstartPlot_ms',0, ...
        'XendPlot_ms',31, ...
        'CAPlength_ms',31), ...
 'fixedPhase', 0,  ...
 'channel',   1, ...
 'MaxdBSPLCalib',   90, ...
 'KHosc',     0, ...
 'fmult',    10, ...
 'CalibBelow90', 0, ...
 'CAPmem_reps',  20, ...
 'threshV', 1.2, ... %for artifact rejection KH 2011 Jun 08
 'threshV2', 1.2,... % for artifact rejection channel 2 JMR nov 21
 'clickYes', 1, ... % added by KH 06Jan2012
 'clickLength_ms', 0.05, ... %KH 10Jan2012
 ... 
 'ear', 'right', ... 
 'rec_channel',1 ... % set recording channel (1=chan 1, 2= chan 2, 3 = Simultaneous) %JMR nov 21
 );

RunLevels_params = struct( ... 
 'nPairs', 1000,...
 'stepdB', 10, ...
... %        'attenMask', [2 1 0 -1 -2 -3], ...
 'attenMask', [0], ...
 'decimateFact', 1, ...
 'saveRepsYes', 0, ... %added by KH 6
 'bMultiOutputFiles', 0 ...
 ); 

Display = struct( ... 
 'Gain', 20000, ...  
 'YLim_atAD', 0.1, ...
 'Voltage', 'atAD' ...
 ); 

AutoLevel_params = struct ( ...  %%added by SP 
 'ManThresh_dBSPL', 35, ...  % fill in with look up table eventually for NormHearing
 'nPairs', 500, ... 
 'stepdB', 10, ... %20, 10 for thresholds
 'attenMask', [], ...
 'decimateFact', 1, ...
 'saveRepsYes', 0, ... %added by KH 6
 'bMultiOutputFiles', 1, ...
 'maxdBSPLtoRUN', 80, ... 
 'zero_to_eighty_override',true,...
 'ReRunFlag', 0, ...
 'dB5Flag', 0, ...
 'ReRun_dBSPL', [], ...
 'dB_below_thresh', 20, ...         % min number of dB to go below manual threshold in stepdB steps in auto list
 'dBaboveTHRman_for_autoTHRcorr', 30, ... %number of dB above manual threshold estimate to use as template in Ken's corr code
 'dBs2RUN',[] ...%what are the dB values to run based on manThresh, MaxCalibValue
 ); 




FIG.handle = figure('NumberTitle','off','Name','ABR Interface','Units','normalized','position',[0.045  0.013  0.9502  0.7474],...
        'Visible','on','MenuBar','none','Tag','AEP_Main_Fig', 'Color', 'w');


FIG.checkbox.fixedPhase = uicontrol(FIG.handle, 'callback', 'ABR(''fixedPhase'');','style','checkbox','Enable','on','Units','normalized','position',[.125 .4 .09 .03],'string','fixedPhase','fontsize',12,'BackgroundColor','w','value',0);
FIG.radio.invCalib      = uicontrol(FIG.handle,'callback','ABR(''calibInit'');','style','radio','Enable','on','Units','normalized','position',[.125 .37 .21 .03],'string','invCalib','fontsize',12,'BackgroundColor','w','value',1);
FIG.radio.fast   = uicontrol(FIG.handle,'callback','ABR(''fast'');','style','radio','Enable','on','Units','normalized','position',[.125 .33 .08 .03],'string','Fast','fontsize',12,'BackgroundColor','w','value',1);
FIG.radio.slow   = uicontrol(FIG.handle,'callback','ABR(''slow'');','style','radio','Enable','on','Units','normalized','position',[.125 .30 .08 .03],'string','Slow','fontsize',12,'BackgroundColor','w');

FIG.fsldr.slider = uicontrol(FIG.handle,'callback','ABR(''slide_freq'');','style','slider','SliderStep',[0.001 0.01],'Enable','on','min',100,'max',1000,'Units','normalized','position',[.35 .175 .525 .04],'Value',1000); %Stimuli.freq_hz/Stimuli.fmult);

FIG.radio.clickYes = uicontrol(FIG.handle,'callback','ABR(''clickYes'');','style','radio','Enable','on','Units','normalized','position',[.89 .175 .08 .03],'string','Click','fontsize',12,'BackgroundColor','w','value',0); %added by KH 06Jan2012

FIG.fsldr.min    = uicontrol(FIG.handle,'style','text','string',num2str(get(FIG.fsldr.slider,'min')),'backgroundcolor',[1 1 1],'Units','normalized','position',[.33 .14 .05 .03],'fontsize',10);
FIG.fsldr.max    = uicontrol(FIG.handle,'style','text','string',num2str(get(FIG.fsldr.slider,'max')),'backgroundcolor',[1 1 1],'Units','normalized','position',[.835 .14 .05 .03],'fontsize',10,'horizontalalignment','right');
% LQ 01/31/05 add callback

FIG.fsldr.val    = uicontrol(FIG.handle,'style','edit','Units','normalized','position',[.5825 .175 .06 .04],'string',num2str(Stimuli.freq_hz),'fontsize',12,'callback', 'ABR(''slide_freq_text'');');
FIG.asldr.slider = uicontrol(FIG.handle,'callback','ABR(''slide_atten'');','style','slider','SliderStep',[1/120 5/120],'Enable','on','min',-120,'max',0,'Units','normalized','position',[.35 .075 .525 .04],'Value',-Stimuli.atten_dB);
FIG.asldr.min    = uicontrol(FIG.handle,'style','text','string',num2str(get(FIG.asldr.slider,'min')),'backgroundcolor',[1 1 1],'Units','normalized','position',[.33 .04 .05 .03],'fontsize',10);
FIG.asldr.max    = uicontrol(FIG.handle,'style','text','string',num2str(get(FIG.asldr.slider,'max')),'backgroundcolor',[1 1 1],...
    'Units','normalized','position',[.825 .04 .05 .03],'fontsize',10,'horizontalalignment','right');
FIG.asldr.val    = uicontrol(FIG.handle,'style','edit','Units','normalized','Userdata',Stimuli.atten_dB,'position',[.5825 .075 .06 .04],'string',num2str(-Stimuli.atten_dB),'fontsize',12,'callback', 'ABR(''slide_atten_text'');');
FIG.statText.memReps =  uicontrol(FIG.handle, 'callback', '', 'style', 'text','Units','normalized', 'position', [.05 .49 .12 .03], 'string', 'Forget Time (reps):','fontsize',12,'BackgroundColor','w');   % added by GE 17Jan2003.
FIG.edit.memReps = uicontrol(FIG.handle,'callback','ABR(''memReps'');','style','edit','Units','normalized','position',[.18 .49 .04 .04],'string',Stimuli.CAPmem_reps,'fontsize',12);
FIG.statText.threshV =  uicontrol(FIG.handle, 'callback', '', 'style', 'text','Units','normalized', 'position', [.05 .54 .12 .03], 'string', 'Reject thresh (V):','fontsize',12,'BackgroundColor','w');   % added by kh 2011Jun08

FIG.edit.threshV = uicontrol(FIG.handle,'callback','ABR(''threshV'');','style','edit','Units','normalized','position',[.18 .54 .04 .04],'string',Stimuli.threshV,'fontsize',12); % KH 2011 Jun 08
FIG.edit.threshV2 = uicontrol(FIG.handle,'callback','ABR(''threshV2'');','style','edit','Units','normalized','position',[.18+.05 .54 .04 .04],'string',Stimuli.threshV2,'fontsize',12); % channel 2 threshold JMR nov 21
FIG.statText.status =  uicontrol(FIG.handle, 'callback', '', 'style', 'text','Units','normalized', 'position', [.05 .9 .25 .03], 'string', ['STATUS (ABR): free running...'],'fontsize',12,'BackgroundColor','w','horizontalalignment','left');   % added by GE 17Jan2003.

FIG.push.x1      = uicontrol(FIG.handle,'callback','ABR(''mult_1x'');','style','pushbutton','Enable','on','Units','normalized','position',[.5 .23 .05 .037],'string','1X','fontsize',12,'fontangle','normal','fontweight','normal','foregroundcolor',[0 0 0]);
FIG.push.x10     = uicontrol(FIG.handle,'callback','ABR(''mult_10x'');','style','pushbutton','Enable','on','Units','normalized','position',[.585 .23 .05 .037],'string','10X','fontsize',12,'fontangle','normal','fontweight','normal','foregroundcolor',[1 1 1]);
FIG.push.x100    = uicontrol(FIG.handle,'callback','ABR(''mult_100x'');','style','pushbutton','Enable','on','Units','normalized','position',[.67 .23 .05 .037],'string','100X','fontsize',12,'fontangle','normal','fontweight','normal','foregroundcolor',[0 0 0]);

FIG.statText.EarLabel = uicontrol(FIG.handle, 'callback', '', 'style', 'text','Units','normalized', 'position', [.1 .24 .1 .05], 'string', 'Audio Output Side:','fontsize',12,'BackgroundColor','w','FontWeight','Bold');
FIG.radio.left   = uicontrol(FIG.handle,'callback','ABR(''left'');', 'style','radio','Enable','on','Units','normalized','position',[.125 .22 .08 .03],'string','Left Ear', 'fontsize',12,'BackgroundColor','w','value',0);
FIG.radio.right  = uicontrol(FIG.handle,'callback','ABR(''right'');','style','radio','Enable','on','Units','normalized','position',[.125 .19 .08 .03],'string','Right Ear','fontsize',12,'BackgroundColor','w','value',1);
FIG.radio.both   = uicontrol(FIG.handle,'callback','ABR(''both'');', 'style','radio','Enable','on','Units','normalized','position',[.125 .16 .08 .03],'string','Both Ears','fontsize',12,'BackgroundColor','w','value',0);
FIG.statText.ChanLabel = uicontrol(FIG.handle, 'callback', '', 'style', 'text','Units','normalized', 'position', [.22 .24 .1 .05], 'string', 'Physiological Signal:','fontsize',12,'BackgroundColor','w','FontWeight','Bold');
FIG.radio.chan_1 = uicontrol(FIG.handle,'callback','ABR(''chan_1'');', 'style','radio','Enable','on','Units','normalized','position',[.125*2 .22 .08 .03],'string','Chan 1 | ABR','fontsize',12,'BackgroundColor','w','value',1);
FIG.radio.chan_2 = uicontrol(FIG.handle,'callback','ABR(''chan_2'');', 'style','radio','Enable','on','Units','normalized','position',[.125*2 .19 .08 .03],'string','Chan 2 | ECochG','fontsize',12,'BackgroundColor','w','value',0);
FIG.radio.Simultaneous = uicontrol(FIG.handle,'callback','ABR(''Simultaneous'');', 'style','radio','Enable','on','Units','normalized','position',[.125*2 .16 .08 .03],'string','Simultaneous','fontsize',12,'BackgroundColor','w','value',0);

FIG.push.run_levels = uicontrol(FIG.handle,'callback','ABR(''run_levels'');','style','pushbutton','Units','normalized',...
    'position',[.06 .726 .09 .09],'string','Run levels...','fontsize',12,'fontangle','normal','fontweight','normal');
FIG.push.Automate_Levels = uicontrol(FIG.handle,'callback','ABR(''Automate_Levels'');','style','pushbutton','Units','normalized',...
    'position',[.18 .726 .09 .09],'string','Auto Levels','fontsize',12,'fontangle','normal','fontweight','normal');
FIG.push.close   = uicontrol(FIG.handle,'callback','ABR(''close'');','style','pushbutton','Units','normalized',...
    'position',[.18 .6 .09 .09],'string','Close','fontsize',12,'fontangle','normal','fontweight','normal');

FIG.asldr.SPL    = uicontrol(FIG.handle,'style','text','string',sprintf('%.1f dB SPL',120+get(FIG.asldr.slider,'val')),...
    'backgroundcolor',[1 1 1],'Units','normalized','position',[.9 .06 .1 .03],'fontsize',10,'horizontalalignment','right');

FIG.push.forget_now = uicontrol(FIG.handle,'callback','ABR(''forget_now'');','style','pushbutton','Units','normalized','position',[.07 .43 .125 .05],'string','Forget NOW','fontsize',12,'fontangle','normal','fontweight','normal');

% 28Apr2004 M.Heinz - Add Gain field, and Voltage-display choice
FIG.statText.gain = uicontrol(FIG.handle, 'callback', '', 'style', 'text','Units','normalized', 'position', [.02 .11 .15 .03], 'string', 'Gain (Electode to AD):','fontsize',12,'BackgroundColor','w');
FIG.edit.gain     = uicontrol(FIG.handle,'callback','ABR(''Gain'');','style','edit','Units','normalized','position',[.17 .11 .07 .04],'string',Display.Gain,'fontsize',12);
FIG.statText.voltDisplay = uicontrol(FIG.handle, 'callback', '', 'style', 'text','Units','normalized', 'position', [.003 .07 .15 .03], 'string', 'Display: voltage','fontsize',12,'BackgroundColor','w');
FIG.radio.atAD    = uicontrol(FIG.handle,'callback','ABR(''atAD'');', 'style','radio','Enable','on','Units','normalized','position',[.135 .07 .13 .03],'string','at AD;  YLim (AD): ', 'fontsize',12,'BackgroundColor','w','value',strcmp(Display.Voltage,'atAD'));
FIG.radio.atELEC  = uicontrol(FIG.handle,'callback','ABR(''atELEC'');','style','radio','Enable','on','Units','normalized','position',[.135 .04 .12 .03],'string','at Electrode','fontsize',12,'BackgroundColor','w','value',~strcmp(Display.Voltage,'atAD'));
FIG.edit.yscale     = uicontrol(FIG.handle,'callback','ABR(''YLim'');','style','edit','Units','normalized','position',[.265 .07 .05 .04],'string',Display.YLim_atAD,'fontsize',12);
